version: '3.8'

services:
  rag-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: task_supernomics-rag-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - rag-network

  frontend-user:
    build:
      context: ./frontend-user
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: task_supernomics-frontend-user
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_APP_NAME=RAG Query System
      - VITE_DEBUG_MODE=true
    ports:
      - "3001:3000"
    depends_on:
      - rag-api
    networks:
      - rag-network

  frontend-admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: task_supernomics-frontend-admin
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_APP_NAME=RAG System Admin
      - VITE_DEBUG_MODE=true
    ports:
      - "3002:3000"
    depends_on:
      - rag-api
    networks:
      - rag-network

  postgres:
    image: pgvector/pgvector:pg15
    container_name: task_supernomics-postgres-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ragpassword
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - rag-network

  redis:
    image: redis:7-alpine
    container_name: task_supernomics-redis-1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - rag-network

  nginx:
    image: nginx:alpine
    container_name: task_supernomics-nginx-1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rag-api
    networks:
      - rag-network

  prometheus:
    image: prom/prometheus:latest
    container_name: task_supernomics-prometheus-1
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - rag-network

  grafana:
    image: grafana/grafana:latest
    container_name: task_supernomics-grafana-1
    ports:
      - "4000:3000"
    volumes:
      - ./docker/grafana/dashboards:/etc/grafana/dashboards
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - rag-network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: task_supernomics-redis-exporter-1
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - rag-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: task_supernomics-postgres-exporter-1
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:ragpassword@postgres:5432/ragdb?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 